name: env_nemo_npd
channels:
  - conda-forge
dependencies:
  - aiobotocore=2.25.2
  - aiohttp=3.13.3
  - botocore=1.40.70
  - cartopy=0.25.0
  - cmocean=4.0.3
  - dask=2025.12.0
  - distributed=2025.12.0
  - eofs=2.0.0
  - flox=0.10.8
  - fsspec=2025.12.0
  - gsw=3.6.20
  - h5netcdf=1.7.3
  - icechunk=1.1.15
  - ipykernel=7.1.0
  - jupyter=1.1.1
  - matplotlib=3.10.8
  - nc-time-axis=1.4.1
  - netcdf4=1.7.3
  - notebook=7.5.1
  - numba=0.63.1
  - numbagg=0.9.4
  - numpy=2.3.5
  - pandas=2.3.3
  - pip=25.3
  - pooch=1.8.2
  - python=3.13.11
  - pystac=1.14.2
  - requests=2.32.5
  - s3fs=2025.12.0
  - scikit-image=0.26.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - shapely=2.1.2
  - tqdm=4.67.1
  - xarray=2025.12.0
  - xesmf=0.9.2
  - zarr=3.1.5
  - pip:
      - pycwt==0.5.0b0
      - "git+https://github.com/NOC-MSM/nemo_cookbook.git"
      - "git+https://github.com/NOC-MSM/OceanDataStore.git"
